CREATE DATABASE LOGIN;
USE LOGIN;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
);

INSERT INTO USUARIOS (USERNAME, PASSWORD) VALUES ('A', 'A')
INSERT INTO USUARIOS (USERNAME, PASSWORD) VALUES ('B', 'B')
INSERT INTO USUARIOS (USERNAME, PASSWORD) VALUES ('C', 'C')